micronaut:
  application:
    name: pixGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/db_keymanager`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

bcb.url: ${BCB_URL:`http://localhost:8082/api/v1/pix`}
itau.url: ${ITAU_URL:`http://localhost:9091/api/v1`}